/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#1a1a1a",
        "on-surface": "#f0f0f0",
        "primary-fixed-dim": "#ffffff",
        "on-tertiary": "#1a1a1a",
        "tertiary-fixed-dim": "#999999",
        "primary": "#ffffff",
        "surface-container": "#111111",
        "on-secondary": "#1a1a1a",
        "surface-tint": "#ffffff",
        "on-error": "#690005",
        "surface-variant": "#1a1a1a",
        "secondary-fixed-dim": "#cccccc",
        "surface-container-lowest": "#000000",
        "outline-variant": "#333333",
        "outline": "#555555",
        "surface": "#000000",
        "background": "#000000",
        "on-secondary-fixed": "#1a1a1a",
        "secondary": "#cccccc",
        "tertiary-fixed": "#999999",
        "primary-fixed": "#ffffff",
        "tertiary": "#888888",
        "on-primary-fixed-variant": "#333333",
        "on-tertiary-container": "#444444",
        "on-secondary-fixed-variant": "#444444",
        "inverse-primary": "#333333",
        "tertiary-container": "#666666",
        "surface-container-low": "#0a0a0a",
        "on-primary": "#000000",
        "surface-container-highest": "#1a1a1a",
        "secondary-fixed": "#e0e0e0",
        "on-tertiary-fixed": "#111111",
        "on-primary-container": "#ffffff",
        "error-container": "#93000a",
        "surface-dim": "#000000",
        "on-background": "#f0f0f0",
        "on-secondary-container": "#bbbbbb",
        "primary-container": "#ffffff",
        "surface-bright": "#222222",
        "inverse-surface": "#f0f0f0",
        "on-tertiary-fixed-variant": "#333333",
        "surface-container-high": "#151515",
        "on-primary-fixed": "#000000",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-surface-variant": "#999999",
        "secondary-container": "#333333"
      },
      fontFamily: {
        "headline": ["'Clash Display'", "sans-serif"],
        "body": ["'Satoshi'", "sans-serif"],
        "label": ["'Clash Display'", "sans-serif"],
        "mono": ["'JetBrains Mono'", "monospace"]
      },
      borderRadius: {"DEFAULT": "0.5rem", "lg": "0.75rem", "xl": "1rem", "full": "9999px"},
    },
  },
  plugins: [],
};
